app = 'clave-take-home'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 5006
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
  min_machines_running = 1

[env]
  XAI_API_KEY=xai-jV5IbcQndvUZIeVq0GzXCSUi7sHyrHgOWr3N9MP9GC2C2bX8bGSSCpJT7CD3ebMp7Lwipx5pjjCFPfTH
  XAI_MODEL=grok-4-1-fast-reasoning
  GROQ_API_KEY=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
  GROQ_MODEL=openai/gpt-oss-20b
  OPENAI_API_KEY=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
  OPENAI_MODEL=gpt-5.2-2025-12-11
  HELICONE_KEY=sk-helicone-ys4ef3i-5sdufaq-tgswrgq-rhotjlq
  DATABASE_URL=postgresql://postgres.vsuobtuknhokyqtjgrnn:claveAdminPass@aws-1-us-east-1.pooler.supabase.com:5432/postgres
  DEBUG=false
